In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 8,4.5

In [2]:
os.chdir('D:\\ai and ml\\')

In [4]:
df1 = pd.read_csv('knn.csv')
print(df1)

          RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]


In [5]:
print(df1.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   Type    214 non-null    int64  
dtypes: float64(9), int64(1)
memory usage: 16.8 KB
None


In [6]:
print(df1.describe())

               RI          Na          Mg          Al          Si           K  \
count  214.000000  214.000000  214.000000  214.000000  214.000000  214.000000   
mean     1.518365   13.407850    2.684533    1.444907   72.650935    0.497056   
std      0.003037    0.816604    1.442408    0.499270    0.774546    0.652192   
min      1.511150   10.730000    0.000000    0.290000   69.810000    0.000000   
25%      1.516522   12.907500    2.115000    1.190000   72.280000    0.122500   
50%      1.517680   13.300000    3.480000    1.360000   72.790000    0.555000   
75%      1.519157   13.825000    3.600000    1.630000   73.087500    0.610000   
max      1.533930   17.380000    4.490000    3.500000   75.410000    6.210000   

               Ca          Ba          Fe        Type  
count  214.000000  214.000000  214.000000  214.000000  
mean     8.956963    0.175047    0.057009    2.780374  
std      1.423153    0.497219    0.097439    2.103739  
min      5.430000    0.000000    0.000000    1

In [7]:
df1.head(2)

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1

In [8]:
x = df1.iloc[:,1:5].values
x

array([[13.64,  4.49,  1.1 , 71.78],
       [13.89,  3.6 ,  1.36, 72.73],
       [13.53,  3.55,  1.54, 72.99],
       [13.21,  3.69,  1.29, 72.61],
       [13.27,  3.62,  1.24, 73.08],
       [12.79,  3.61,  1.62, 72.97],
       [13.3 ,  3.6 ,  1.14, 73.09],
       [13.15,  3.61,  1.05, 73.24],
       [14.04,  3.58,  1.37, 72.08],
       [13.  ,  3.6 ,  1.36, 72.99],
       [12.72,  3.46,  1.56, 73.2 ],
       [12.8 ,  3.66,  1.27, 73.01],
       [12.88,  3.43,  1.4 , 73.28],
       [12.86,  3.56,  1.27, 73.21],
       [12.61,  3.59,  1.31, 73.29],
       [12.81,  3.54,  1.23, 73.24],
       [12.68,  3.67,  1.16, 73.11],
       [14.36,  3.85,  0.89, 71.36],
       [13.9 ,  3.73,  1.18, 72.12],
       [13.02,  3.54,  1.69, 72.73],
       [12.82,  3.55,  1.49, 72.75],
       [14.77,  3.75,  0.29, 72.02],
       [12.78,  3.62,  1.29, 72.79],
       [12.81,  3.57,  1.35, 73.02],
       [13.38,  3.5 ,  1.15, 72.85],
       [12.98,  3.54,  1.21, 73.  ],
       [13.21,  3.48,  1.41, 72.64],
 

In [9]:
y = df1.iloc[:,-1].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7], dtype=int64)

In [10]:
from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
x = sc_x.fit_transform(x)
print(x)

[[ 2.84953261e-01  1.25463857e+00 -6.92441924e-01 -1.12708201e+00]
 [ 5.91817180e-01  6.36168030e-01 -1.70460232e-01  1.02319067e-01]
 [ 1.49933137e-01  6.01422494e-01  1.90911708e-01  4.38786730e-01]
 [-2.42852679e-01  6.98709995e-01 -3.10993765e-01 -5.29737012e-02]
 [-1.69205338e-01  6.50066245e-01 -4.11374859e-01  5.55256306e-01]
 [-7.58384063e-01  6.43117137e-01  3.51521459e-01  4.12904602e-01]
 [-1.32381668e-01  6.36168030e-01 -6.12137048e-01  5.68197370e-01]
 [-3.16500020e-01  6.43117137e-01 -7.92823018e-01  7.62313330e-01]
 [ 7.75935532e-01  6.22269816e-01 -1.50384013e-01 -7.38850093e-01]
 [-5.00618371e-01  6.36168030e-01 -1.70460232e-01  4.38786730e-01]
 [-8.44305960e-01  5.38880530e-01  2.31064145e-01  7.10549074e-01]
 [-7.46109506e-01  6.77862673e-01 -3.51146202e-01  4.64668858e-01]
 [-6.47913052e-01  5.18033208e-01 -9.01553568e-02  8.14077586e-01]
 [-6.72462165e-01  6.08371602e-01 -3.51146202e-01  7.23490138e-01]
 [-9.79326084e-01  6.29218923e-01 -2.70841327e-01  8.27018650e

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)
print(x.shape)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(214, 4)
(171, 4)
(43, 4)
(171,)
(43,)


In [12]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier()
KNN.fit (x_train,y_train)

KNeighborsClassifier()

In [13]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
KNN.fit(x_train,y_train)
print(KNN)

KNeighborsClassifier()


In [14]:
y_pred = KNN.predict(x_test)
print(y_pred)

[1 1 1 2 1 2 2 1 7 7 1 1 1 1 2 2 7 2 2 2 1 2 2 2 7 1 1 7 2 7 1 1 2 1 7 1 1
 1 1 7 2 2 7]


In [16]:
print(y_test)

[1 1 1 2 1 5 5 1 7 7 3 2 1 1 2 1 7 2 2 2 2 2 7 2 7 1 3 7 7 5 2 2 3 1 7 1 2
 1 1 6 6 2 5]


In [17]:
from sklearn.metrics import r2_score
accuracy = r2_score(y_test,y_pred)
print(accuracy)

0.521828665568369


In [19]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred,zero_division=0))

              precision    recall  f1-score   support

           1       0.63      0.92      0.75        13
           2       0.53      0.62      0.57        13
           3       0.00      0.00      0.00         3
           5       0.00      0.00      0.00         4
           6       0.00      0.00      0.00         2
           7       0.67      0.75      0.71         8

    accuracy                           0.60        43
   macro avg       0.31      0.38      0.34        43
weighted avg       0.48      0.60      0.53        43



In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix (y_test, y_pred)
print(cm)

[[12  1  0  0  0  0]
 [ 5  8  0  0  0  0]
 [ 2  1  0  0  0  0]
 [ 0  2  0  0  0  2]
 [ 0  1  0  0  0  1]
 [ 0  2  0  0  0  6]]


In [21]:
y_pred = KNN.predict(x)
print(y_pred)

[1 1 2 1 1 2 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 2
 2 2 2 2 1 2 2 2 1 2 6 2 2 2 2 2 2 1 2 2 2 2 1 1 2 2 2 2 1 1 1 5 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 2 2 2 2 2 2 1 2 2 1 2 2 2 2 1 1 2 1 2 1 1
 1 1 2 1 3 1 1 1 3 1 2 2 2 3 1 5 2 5 2 2 7 7 2 5 5 2 2 5 6 3 6 6 7 7 7 2 6
 2 2 3 2 3 6 7 7 7 7 7 7 7 7 7 7 2 7 7 7 7 7 7 7 7 7 7 7 7]


In [23]:
df_ypred = pd.DataFrame(y_pred,columns = ['Prediction'])
result = pd.concat ([df1,df_ypred],axis = 1)
print(result.head(50))

         RI     Na    Mg    Al     Si     K     Ca    Ba    Fe  Type  \
0   1.52101  13.64  4.49  1.10  71.78  0.06   8.75  0.00  0.00     1   
1   1.51761  13.89  3.60  1.36  72.73  0.48   7.83  0.00  0.00     1   
2   1.51618  13.53  3.55  1.54  72.99  0.39   7.78  0.00  0.00     1   
3   1.51766  13.21  3.69  1.29  72.61  0.57   8.22  0.00  0.00     1   
4   1.51742  13.27  3.62  1.24  73.08  0.55   8.07  0.00  0.00     1   
5   1.51596  12.79  3.61  1.62  72.97  0.64   8.07  0.00  0.26     1   
6   1.51743  13.30  3.60  1.14  73.09  0.58   8.17  0.00  0.00     1   
7   1.51756  13.15  3.61  1.05  73.24  0.57   8.24  0.00  0.00     1   
8   1.51918  14.04  3.58  1.37  72.08  0.56   8.30  0.00  0.00     1   
9   1.51755  13.00  3.60  1.36  72.99  0.57   8.40  0.00  0.11     1   
10  1.51571  12.72  3.46  1.56  73.20  0.67   8.09  0.00  0.24     1   
11  1.51763  12.80  3.66  1.27  73.01  0.60   8.56  0.00  0.00     1   
12  1.51589  12.88  3.43  1.40  73.28  0.69   8.05  0.00  0.24  